name: github-actions
on: push

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: The triggering event
        run: echo "The triggering event is ${{ github.event_name }}."
      - name: The OS
        run: echo "The OS name is ${{ runner.os }}"
